### ISSUE TITLE
Metrics / collect metrics for V2 launch tracking

### ISSUE THREAD

**Issue by xinaxu** [data-preservation-programs/singularity#115]

**Comment by celine3650** [comment]
https://singularity-metrics-dashboard.vercel.app/

**Comment by anjor** [comment]
What's pending here? If there's feedback that needs to be actioned, could we break that down in issues?

**Comment by xinaxu** [comment]
The dashboard only have V1 metrics. V2 does not yes report any metrics. Yes
so we need an item to have v2 report same metrics as v1, and another item
for any additional metrics we want

**Comment by celine3650** [comment]
Here is the feedback that coming out of the ICU meeting today. 

1. Get you the graphing library that Fil+ dashboard uses

2. Numbers on the top are not important, reduce the amount of presence compared to graphs, might just need at most 4 big numbers on the top. No need for # of files etc, just need # of data in Pib
3. Move from line graphs to stacked bar for a clear/clean read
4. Total deal with the state-> turn into stacked bar, show the total (See starboard's circulating supply graph) and rename to "states of deals / states of pipeline"
5. What the total seal mean? sealed? = active + slashed + expired --- maybe not useful to juan, he cares more about states
6. expiration forecast
7. bottom graph: client name cannot be dataset -> lets talk to Fil+ team about changing the label to the github account when we don't know who it is, or we can use the github submission name to just slice by submit person
or relabel the graph to dataset OR client ID
8. clickable stacked bars, instead of hover, to click through day / week / month, similar like the Starboard dashboard
9. region splits on singularity usage
10. data preparers matter, now the LDN has the data preparers session, can we pull that as well? --
files count at top is awesome, clients is good too - graph these
