### ISSUE TITLE
How does chunk get created when push item is called manually?

### ISSUE THREAD

**Issue by hannahhoward** [data-preservation-programs/singularity#152]
The current motion API creates a data source that is in the Created state, then uses the Push Item API to manually notify singularity a new item is present. The Push Item API endpoint will create the Item, and Item Parts, but it does not create a Chunk. So if there is a dataset worker running, it won't get picked up for scanning (intentionally) because the source is in the Created state, but it also won't get picked up for Packing, because there is no Chunk model to pack. The question is, if you use the PushItem API, how do we expect Chunk's to be created? Is it appropriate to put the data set in a state it can be rescanned? Or should there be some manual Chunk creation call (which would then require the caller to figure out how item parts go together)

**Comment by xinaxu** [comment]
Thanks for pointing this out. This is a known issue to me that the dataset worker did not handle the case where it should not scan the data source but only pick up remaining items that do not belong to a chunk.
The code is actually there but not activated nor tested. 
https://github.com/data-preservation-programs/singularity/blob/a9f43f1e23d3a7d4a44aa946ed06e0354a12a5e6/service/datasetworker/scan.go#L137

The flow should be, the push API should not create new chunks and the dataset worker should pick up remaining item parts and assign them into chunks. Hence the fix we need to do is
1. add / change an option in datasource creation indicating that this datasource should never be scanned
2. set scanSource to false in above code line

There is one more thing I need to implement - a max duration to wait before the dataset worker pick up the remaining items to a CAR file - so that remaining items won't be pending forever
