### ISSUE TITLE
For Retrieval: How to link back to deals from a DataSetID / Source?

### ISSUE THREAD

**Issue by hannahhoward** [data-preservation-programs/singularity#71]
I am looking at the data model, and it's not clear for the retrieval case how source/directory/item/itempart/chunk/car etc get linked to deals that are made.

A CAR model is passed to the MakeDeal command, but there's no link stored to the CAR in the model for Deal.

The reason this matters is I assume that for retrieval, we're eventually going to have to have essentially an "Unpack" process where the requested retrieval is a DataSetID, Source, Directory, or Item.

Am I missing something about how you imagine the data model to work?

**Comment by xinaxu** [comment]
For itempart, it should belongs to a Chunk which 1:1 maps to a CAR which you can discover deals using same piece_cid - There is no foreign key constraint for piece_cid between CAR and Deal because
1. we may want to separate dataset prep and deal making database in the future
2. we want to record all deals made by relevant clients even if this deal does not belong to the dataset prepared by Singularity

For item/directory/source, it is no 1:1 mapping to Deal or Car, because they can be splitted across multiple CARs. For item, it can have multiple itemparts, each of which has a chunk_id. For source/dataset, you should be able to list all CARs belonging to a dataset. For directory, it will need some table join to get you all relevant deals.

I need a bit more information for what you mean by "unpack" process. I was under impression that retrieval should just work (for HTTP/GS/BS) with a single source/directory/file CID assuming all relevant CAR files are sealed.

**Comment by hannahhoward** [comment]
@xinaxu that makes sense -- as long as there are indexes for PieceCID in the DB on the relevant models it's fine to use that to link CARs and Deals, even without a foreign key constraint. Sorry for missing that. And I get the goal of seperation.

When I say unpack process, what I am starting from is that any Source, Directory, or Item may be large enough to span multiple deals, and moreover, we want to return the original Directory/Item in a flat format. So we'll need to map from Source/Directory/Item to deals and then execute potentially multiple retrievals, and then reassemble everything.
