### ISSUE TITLE
Singularity as a code library vs API/CLI

### ISSUE THREAD

**Issue by hannahhoward** [data-preservation-programs/singularity#83]
In writing https://github.com/filecoin-project/motion/pull/29, I've noticed that singularity really isn't well setup to run as a high level code library.

It seems if you want to have abstractions, Singularity really wants to run in a separate process and have you make calls over the HTTP api or by running CLI commands.

Otherwise, as is evident in that PR, you're quickly making direct calls to gorm.DB, which seems odd.

It would be nice to expose a top level library API that would wrap gorm.DB and provide the same functions the API does. 

It seems like the code in the "handler" folder does some of this abstraction, but only on the level of individual functions. Also, there are many direct DB queries spread out over api & cmd structures despite many functions being in handler. Is all DB interaction supposed to happen in Handler and this is an incomplete refactor? Or am I misunderstanding the point of the handler folder?

If DB interactions were contained to a folder, that would make building a `./lib` with a top level API quite straightforward. As it is, it seems like Singularity really doesn't want to be run in process, as a process boundary really seems currently the only way to get a higher level abstraction around Singularity.

Alternatively, let's just recognize Singularity is not meant to be used as a library and start planning a multi-process deployment for motion.

**Comment by xinaxu** [comment]
The initial purpose of handler is to offer reusable handlers that can be used by both CLI and web API. There are exceptions, i.e.
1. run service which does not make sense to be a web API
2. dashboard related API that only represents the view of internal dashboard which does not make sense to have a relevant CLI
For pushItem, it should be applicable for both CLI and web API but I did not finish the refactoring. Thanks for moving it to the handler package.

The way I imagine how you would like to interact with SIngualrity is to call those functions in the handler package which acts same as calling the API or performing the CLI, i.e. you would like to create a dataset using DatasetCreateHandler rather than manually creating a dataset model.

**Comment by hannahhoward** [comment]
@xinaxu this confirms my view of what I imagine the handlers to be, and it wouldn't be that hard to make a programmatic library interface that simply wraps the dependencies (Gorm etc) and then calls the handlers.

**Comment by xinaxu** [comment]
let's chat on Monday for what this should look like

**Comment by xinaxu** [comment]
we're going with swagger API client
